# Starter pipeline
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: "Build, Test, and Publish"
  jobs:
  - job: Build
    timeoutInMinutes: 4
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Build complete"   # Test build for success 
    
  - job: Test
    timeoutInMinutes: 5
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Testing complete"

  - job: PublishBuild
    timeoutInMinutes: 4
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Publishing to my artifactory"   # Publishing to artifactory

- stage: QA_Envi
  displayName: "Deployed Prod QA Envi"
  jobs:
  - job: Deploy
    timeoutInMinutes: 6
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Deployed to QA"   #App deployed to QA envi

- stage: Stage_Envi
  displayName: "Deployed to stage Envi"
  jobs:
  - job: Deploy
    timeoutInMinutes: 4
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Deployed to stage"   #App deployed to stage envi

- stage: Prod_Envi
  displayName: " Deployed Prod Envi"
  jobs:
  - job: Deploy
    timeoutInMinutes: 5
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "Deployed to Prod"   #App deployed to Prod envi
